name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
      - run: pnpm install
      - run: pnpm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
